import {
  FiHome,
  FiFileText,
  FiCreditCard,
  FiShield,
  FiHeart,
  FiTarget,
  FiMic,
} from 'react-icons/fi';

/**
 * BFSI Platform — All 7 Learning Modules
 * Defines unlock requirements, metadata, and point values per FRD v1.0
 */
export const MODULES_CONFIG = [
  {
    id: 'loans_module_1',
    number: 1,
    title: 'Types of Loans',
    subtitle: 'Home Loan Lifecycle & Product Knowledge',
    icon: FiHome,
    color: '#3b82f6',
    bg: '#eff6ff',
    totalTopics: 11,
    totalPoints: 270,
    estimatedHours: '2–3 hrs',
    tags: ['Core', 'Beginner'],
    unlockRequirement: null, // always available
  },
  {
    id: 'operations_module_2',
    number: 2,
    title: 'Operations, KYC & Compliance',
    subtitle: 'Tools, Process and Documentation',
    icon: FiFileText,
    color: '#8b5cf6',
    bg: '#f5f3ff',
    totalTopics: 9,
    totalPoints: 200,
    estimatedHours: '1.5–2 hrs',
    tags: ['Process', 'Intermediate'],
    unlockRequirement: { type: 'single', moduleId: 'loans_module_1', minCompletion: 0.5 },
  },
  {
    id: 'credit_module_3',
    number: 3,
    title: 'Credit & CIBIL',
    subtitle: 'Credit scores, report analysis, improving eligibility',
    icon: FiCreditCard,
    color: '#10b981',
    bg: '#f0fdf4',
    totalTopics: 9,
    totalPoints: 250,
    estimatedHours: '2 hrs',
    tags: ['Credit', 'Intermediate'],
    unlockRequirement: { type: 'single', moduleId: 'loans_module_1', minCompletion: 1.0 },
  },
  {
    id: 'life_insurance_module_4',
    number: 4,
    title: 'Life Insurance',
    subtitle: 'Term, ULIP, premium structures, claim process',
    icon: FiShield,
    color: '#f59e0b',
    bg: '#fffbeb',
    totalTopics: 10,
    totalPoints: 250,
    estimatedHours: '2 hrs',
    tags: ['Insurance', 'Intermediate'],
    unlockRequirement: { type: 'single', moduleId: 'loans_module_1', minCompletion: 1.0 },
  },
  {
    id: 'health_insurance_module_5',
    number: 5,
    title: 'Health Insurance',
    subtitle: 'Cashless claims, exclusions, family floater',
    icon: FiHeart,
    color: '#ef4444',
    bg: '#fef2f2',
    totalTopics: 9,
    totalPoints: 250,
    estimatedHours: '2 hrs',
    tags: ['Insurance', 'Advanced'],
    unlockRequirement: { type: 'single', moduleId: 'credit_module_3', minCompletion: 1.0 },
  },
  {
    id: 'sales_module_6',
    number: 6,
    title: 'Sales & Objection Handling',
    subtitle: 'SPIN selling, discovery framework, closing techniques',
    icon: FiTarget,
    color: '#f97316',
    bg: '#fff7ed',
    totalTopics: 9,
    totalPoints: 250,
    estimatedHours: '2–3 hrs',
    tags: ['Sales', 'Advanced'],
    unlockRequirement: {
      type: 'multi',
      moduleIds: ['loans_module_1', 'credit_module_3', 'life_insurance_module_4'],
    },
  },
  {
    id: 'interview_module_7',
    number: 7,
    title: 'Interview Preparation',
    subtitle: 'Mock interviews and tips to be successful',
    icon: FiMic,
    color: '#6366f1',
    bg: '#eef2ff',
    totalTopics: 8,
    totalPoints: 200,
    estimatedHours: '1.5 hrs',
    tags: ['Career', 'Advanced'],
    unlockRequirement: { type: 'single', moduleId: 'loans_module_1', minCompletion: 1.0 },
  },
];
